### ISSUE TITLE
Make 18F logo a link to '/'

### ISSUE THREAD

**Issue by adelevie** [18F/iaa-mvp#10]
@andrewmaier can you do this?

**Comment by adelevie** [comment]
The layout code is in https://github.com/18F/iaa-mvp/blob/master/views/layout.html

**Comment by adelevie** [comment]
Part of https://trello.com/c/F4FCvHI1/20-as-iaa-team-i-would-like-the-current-site-to-have-navigation-so-as-to-work-better-during-demos.

**Comment by andrewmaier** [comment]
Will do :)

**Comment by andrewmaier** [comment]
Fixed this past sprint. Closing! cc @adelevie
