### ISSUE TITLE
API

### ISSUE THREAD

**Issue by vdavez** [18F/iaa-mvp#8]
Eventually, we'll need to provide a RESTful API so that we can load information from an IAA into  different systems downstream from the IAA process.

**Comment by adelevie** [comment]
Read API should be pretty simple. Is there an example integration you have in mind? (even if it doesn't exist yet)

**Comment by adelevie** [comment]
Closing for now, but we should add this to [Trello](https://trello.com/b/1DeHImIq/iaa-forms), @vzvenyach.
